image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals.
# https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      npm install &&
      npm run build
    command: npm run test

# Enable prebuilds of your project to enable faster workspace start times.
# https://www.gitpod.io/docs/prebuilds/#configure-the-github-app
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
